---
- name: A playbook to demo automating against RedFish APIs using community.general collection
  hosts: redfish_apis    # group name
  connection: local      # we need to run HTTP(s) to talk to the RedFish APIs
  gather_facts: false

  # collections:
  # - community.general      # to update / install, "ansible-galaxy collection install community.general"

  tasks:

         - name: Graceful restart
           community.general.redfish_command:
               category: Systems
               command: PowerGracefulRestart
               # resource_id: 
               baseuri: "{{ baseuri }}"
               username: "{{ username }}"
               password: "{{ password }}"
